name: "conan_cache"
description: "caching for conan packages"

runs:
  using: "composite"
  steps:
    - name: cache
      uses: actions/cache@v2
      with:
        path: "${{ env.CONAN_USER_HOME }}"
        key: "${{ hashFiles('./conan/conanfile.py')}}"
