name: build-and-test

on: [push, pull_request]

env:
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-20.04-clang-14
          - ubuntu-20.04-clang-13
          - ubuntu-20.04-clang-12
          - ubuntu-20.04-gcc-11
          - ubuntu-20.04-gcc-10
          - ubuntu-20.04-gcc-9
    container: "maciejpatro/${{ matrix.image }}"
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/conan-cache
      - name: Build and test
        run: |
          cmake -B release -DCMAKE_BUILD_TYPE=Release -G Ninja
          cmake --build release
          ctest --test-dir release -VV
      - uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "./release/*_tests.xml"
